name: cimat
description: Gerenciar materiais do setor.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Gerenciador de estados
  get: ^4.6.5
  # Google
  google_fonts: ^4.0.3
  # Back4app
  parse_server_sdk_flutter: ^3.1.3
  # image
  image_picker: ^0.8.6+2
  image_picker_for_web: ^2.1.10
  # outros
  url_launcher: ^6.1.9
  validatorless: ^1.2.3
  pdf: ^3.9.0
  printing: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/